### PR TITLE
Add SVG table parser for svg color font parsing

### PR DESCRIPTION
**Pull request by kingschnulli**
see https://www.colorfonts.wtf/ and https://www.microsoft.com/typography/otspec/svg.htm

This currently only parses the data, maybe the utilities could add some methods to draw all of this into a canvas context. What do you think?

### CODE REVIEW

**Comment by photopea** [comment]
As I understand, you implemented just parsing, not the rendering mechanism?

**Comment by kingschnulli** [comment]
Yes this is currently just the parsing part - i tested the output with a simple test script that just draws the parsed svg information into the page. This looks good so far, as there is just a limited set of fonts that have this feature currently I could only test a few.

I wanted to discuss what would be the best way to implement the rendering before adding that.

**Comment by photopea** [comment]
I already implemented the SVG rendering, I will update it here today.

**Comment by photopea** [comment]
I just updated the library, I slightly edited your SVG.js (added SVG parsing). Try to open your colored fonts in https://photopea.github.io/Typr.js/ :)

**Comment by kingschnulli** [comment]
This is awesome, thanks for implementing this part.

**Comment by photopea** [comment]
Thank you for telling me that such thing exists :D

**Comment by photopea** [comment]
You can try it [HERE](https://www.photopea.com/?p=%7B%22files%22:%5B%22https://www.photopea.com/api/img2/fnt_preview.psd%22%5D,%22resources%22:%5B%22https://www.photopea.com/api/img2/fnts/Abelone-FREE.otf%22,%22https://www.photopea.com/api/img2/fnts/BungeeColor-Regular_svg.ttf%22,%22https://www.photopea.com/api/img2/fnts/Gilbert-Color%20Bold-Preview_1004.otf%22,%22https://www.photopea.com/api/img2/fnts/NTBixa-Color.otf%22,%22https://www.photopea.com/api/img2/fnts/Playbox-FREE.otf%22%5D,%22environment%22:%7B%7D%7D).

**Pull request closed without merging**
