### PR TITLE
Total overhaul PR

### PR DESCRIPTION
**Pull request by wuoarh**
Hi there!

I just wanted to submit a big bulk of changes you may not agree with at all.

As mentioned briefly in the readme, I
* converted from global scope to import/export
** for example, this brings with it a different syntax how the typr object is filled with functionality. But I tried to preserve the existing functionality doing this.
* replaced vars with consts/lets
* saved array lengths instead of re-evaluating them in loops

I didn't manage to apply those changes in a convenient/easily reviewable way, as I made them in a different repo and just moved them over to my fresh fork.

Please excuse this PR, but I wanted to contribute back what I found most necessary myself.
I hope, those changes and the reason for doing so can be understood and appreciated.

I do this, because I like typr very much. It's a great library and it's my choice in regards of functionality and performance. But I think, it needs to evolve.

I'm also concerned about the large (?) number of forks. I'm afraid of missing out on updates and features. I hope, this PR can be accepted some time, and hope to benefit from other PRs as well.

I get if this changeset is too unmanagable to give it a proper look. But, please, give it a try.

With kind regards,
wuoarh

### CODE REVIEW

**Comment by photopea** [comment]
Hi, I am afraid I can not accept this pull request.

I write JS in a certain way, and I find using "var" nicer, than switching between var / const / let. Also, I don't like to use JS modules, as they are bound to specific files, and you can not merge them into one file just by concatenating multiple files. I always write JS, that works in browsers "as is".

But feel free to create your own fork.

**Comment by wuoarh** [comment]
Hi!

Thank you for having a look at this huge mess! I completely understand that.

Sad to hear that our use cases don't seem to fit together that well.

I had some versions of my response and decided to go for the shooort one... I could discuss this further for quite some time 😄 

Maybe some day it's a better fit :) Thanks for your time again.

Best, Jan

**Comment by laptou** [comment]
Hello @wuoarh, I am interested in this fork, but I can't find it. Can you tell me where to look please?

**Comment by wuoarh** [comment]
Hey!
you can still check that fork out at https://github.com/wuoarh/Typr.js , but:
- it is not maintained
- it is heavily derived
- you won't see the progress of how the fork was refactored (see my "mess-comments") - I planned on doing a more clean fork, which I didn't :/

Still, I'm glad to get feedback and thank you for the interest! I still consider it a step forward for a great lib :)

**Pull request closed without merging**
