### PR TITLE
Consolidated fixes

### PR DESCRIPTION
**Pull request by fredli74**
Various fixes I have made for a typescript version I use in my own projects. I have tried to isolate pure Typr.js fixes and make them as un-intrusive as possible for easier merging.

### CODE REVIEW

**Comment by fredli74** [comment]
According to opentype specs, multiple GPOS adjustments on the same pair should be accumulated. This also corrects a bug I introduced in efb1f66efa9fe09089812621f0229a06df2f2b66

**Comment by lojjic** [comment]
@fredli74 As you've probably seen, Typr.js has moved on to a WASMified Harfbuzz implementation for most layout features, so there seems there's no chance of your fixes getting back in to the primary branch here.

I personally still have need of the pure JS implementation, and I'd like to get your fixes (particularly the ones in `getPairAdjustment`), so I'm trying to figure out how best to go about that. I see these options:

* Create a branch in this photopea fork for the pure JS version, to which fixes could be applied (any interest there, @photopea ?)
* Treat @fredli74's [Typr.ts](https://github.com/fredli74/Typr.ts) fork as the new "official" maintenance branch
* Create a new fork somewhere else and merge in your fixes

Thoughts?

**Comment by photopea** [comment]
Guys, our old code was buggy, and this pull request could probably make it a little less buggy.

I really think you should switch to HarfBuzz, if you render anything non-trivial. I think you should not care about browsers without WASM support, as they are slowly disappearing (and you should help them disappear faster by making WASM mandatory).

**Comment by lojjic** [comment]
Different tools for different use cases and all that.

Should I take your response as not being interested in a maintenance branch in this repo?

**Comment by photopea** [comment]
No, I would like to have just one branch here. You can make and maintain your own branch.

**Comment by lojjic** [comment]
Fair enough, thanks for considering. :)

@fredli74 would you be interested your fork becoming the canonical maintenance branch? Otherwise, I will create a fork myself, but fewer forks is better IMO.

**Comment by fredli74** [comment]
I actually do not use typr.js to render complete text paths but to convert fonts into a proprietary font format. Moving forward, I will continue to need the OpenType font table lookups and things like getPairAdjustment. So maybe this is where we part ways? ☺️

@lojjic Sure, you pull, I pull, either way, is fine by me. As you maybe noticed, my master is the typescript wrapper and the typr.js branch is the pure js forked version with fixes.

**Pull request closed without merging**
